keys:
  - &users:
    - &primary age10pzhycy2vu2putmw4agnrhs9r9p5ud6ck9vv95z2d2uc6mcuze2qzv5ezw
  - &hosts:
    - &vega age1xqm2frdrzpya4maje63xrfjdnr26ljr8u0jqd4djswreuzhez3pq4tpx0y
    - &lua age1jq5mfsvzfcz0w5vsdq7w3ycyxh9wgmk7mu9xxnk70xqwumxgyanssp2h9q
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *primary
          - *vega
          - *lua
